name: jaguar_logger
description: Level logger with backends for file, http and postgres with support for log rotation
version: 1.0.0
homepage: https://github.com/Jaguar-dart/logger

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  date_format: ^1.0.8
  stack_trace: ^1.9.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
