name: jaguar_logger
description: Level logger with backends for file, http and postgres with support for log rotation
version: 1.0.1
homepage: https://github.com/Jaguar-dart/logger

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  date_format: ^2.0.5
  stack_trace: ^1.10.0
  pedantic: ^1.11.1
  path: ^1.8.0

dev_dependencies:
  test: ^1.20.1

